FROM golang:1.22-alpine

WORKDIR /app

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN go build -o main ./app/cmd/api

EXPOSE 3030

CMD ["./main"]