version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3030:3030"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - app_network

  www:
    build:
      context: .
      dockerfile: Dockerfile.www
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: 